<script lang="ts">
  import { jsPDF } from 'jspdf';

  interface Props {
    patientId: string;
  }

  let { patientId }: Props = $props();

  let dateFrom = $state('');
  let dateTo = $state('');
  let isGenerating = $state(false);

  // Default date range: last 30 days
  $effect(() => {
    const now = new Date();
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    dateTo = formatInputDate(now);
    dateFrom = formatInputDate(thirtyDaysAgo);
  });

  function formatInputDate(d: Date): string {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${y}-${m}-${day}`;
  }

  async function generateReport() {
    isGenerating = true;

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      // Title
      doc.setFontSize(18);
      doc.text('CDSS', pageWidth / 2, y, { align: 'center' });
      y += 10;
      doc.setFontSize(12);
      doc.text('Pediatric Health Trend Report', pageWidth / 2, y, { align: 'center' });
      y += 14;

      // Separator line
      doc.setDrawColor(200, 200, 200);
      doc.line(20, y, pageWidth - 20, y);
      y += 10;

      // Patient info
      doc.setFontSize(10);
      doc.text(`Patient ID: ${patientId}`, 20, y);
      y += 7;
      doc.text(`Report period: ${dateFrom} ~ ${dateTo}`, 20, y);
      y += 7;
      doc.text(`Generated: ${new Date().toISOString().split('T')[0]}`, 20, y);
      y += 14;

      // Trend charts placeholder
      doc.setFontSize(12);
      doc.text('Trend Charts', 20, y);
      y += 8;

      doc.setFontSize(9);
      doc.setTextColor(140, 140, 140);
      doc.text('[Trend chart images will be embedded in future versions]', 20, y);
      y += 14;
      doc.setTextColor(0, 0, 0);

      // Alert summary table header
      doc.setFontSize(12);
      doc.text('Alert Summary', 20, y);
      y += 8;

      doc.setFontSize(9);
      doc.setFillColor(240, 240, 240);
      doc.rect(20, y, pageWidth - 40, 7, 'F');
      doc.text('Date', 22, y + 5);
      doc.text('Risk Level', 62, y + 5);
      doc.text('Status', 102, y + 5);
      doc.text('Rationale', 132, y + 5);
      y += 10;

      // Placeholder row
      doc.setTextColor(140, 140, 140);
      doc.text('[Alert data will be populated from Dexie in future versions]', 22, y + 5);
      y += 10;
      doc.setTextColor(0, 0, 0);

      // Footer
      const footerY = doc.internal.pageSize.getHeight() - 15;
      doc.setFontSize(8);
      doc.setTextColor(160, 160, 160);
      doc.text(
        'Generated by CDSS Pediatric Clinical Decision Support System',
        pageWidth / 2,
        footerY,
        { align: 'center' },
      );

      // Save
      doc.save(`cdss-report-${patientId}-${dateFrom}-${dateTo}.pdf`);
    } finally {
      isGenerating = false;
    }
  }
</script>

<div class="report-export" aria-label="匯出報告">
  <h3 class="export-title">匯出報告</h3>

  <div class="date-range">
    <div class="date-field">
      <label for="date-from" class="date-label">開始日期</label>
      <input
        id="date-from"
        type="date"
        class="date-input"
        bind:value={dateFrom}
        aria-label="報告開始日期"
      />
    </div>
    <div class="date-field">
      <label for="date-to" class="date-label">結束日期</label>
      <input
        id="date-to"
        type="date"
        class="date-input"
        bind:value={dateTo}
        aria-label="報告結束日期"
      />
    </div>
  </div>

  <button
    class="export-btn"
    onclick={generateReport}
    disabled={isGenerating || !dateFrom || !dateTo}
    aria-label="產生 PDF 報告"
  >
    {isGenerating ? '產生中...' : '產生報告'}
  </button>
</div>

<style>
  .report-export {
    display: flex;
    flex-direction: column;
    gap: var(--space-4);
    padding: var(--space-4);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-md);
    background-color: var(--bg-surface);
  }

  .export-title {
    margin: 0;
    font-size: 1rem;
    font-weight: 600;
    color: var(--color-text-base);
  }

  .date-range {
    display: flex;
    flex-wrap: wrap;
    gap: var(--space-4);
  }

  .date-field {
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
  }

  .date-label {
    font-size: 0.8rem;
    font-weight: 500;
    color: var(--color-text-muted);
  }

  .date-input {
    min-height: 44px;
    padding: var(--space-2) var(--space-3);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-md);
    font-size: 0.875rem;
    color: var(--color-text-base);
    background-color: var(--bg-base);
  }

  .date-input:focus {
    outline: 2px solid var(--color-accent);
    outline-offset: -1px;
    border-color: var(--color-accent);
  }

  .export-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-height: 44px;
    padding: var(--space-3) var(--space-6);
    border: none;
    border-radius: var(--radius-md);
    font-size: 0.875rem;
    font-weight: 600;
    color: #fff;
    background-color: var(--color-accent);
    cursor: pointer;
    transition: background-color 0.2s ease;
    align-self: flex-start;
  }

  .export-btn:hover:not(:disabled) {
    background-color: var(--color-accent-hover);
  }

  .export-btn:focus-visible {
    outline: 2px solid var(--color-accent);
    outline-offset: 2px;
  }

  .export-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
