// AUTO-GENERATED by scripts/build-content-index.ts — do not edit.
// Source: src/data/education/content-relevance.yaml clinicalAlertEducation section.
export const CLINICAL_EDUCATION: Record<string, string[]> = {
  "activity_level": ["exercise-guide"],
  "sleep_quality": ["sleep-hygiene"],
  "spo2": ["respiratory-care"],
  "sugar_intake": ["diet-control"],
};
